include("../src/Phunky.jl")
using .Phunky
using Plots
using NumericalIntegration

ebdata = ebInputData("examples/input.nml")
deconvolution = DeconvData(ebdata)
sodata = qeIfc2Output("examples/espresso.ifc2")

# We supply our PhaseSpace struct with points generated by elphbolt
# q1_file = readlines("examples/phasespace-verify/ph.wavevecs_ibz")
# numq1 = size(q1_file, 1)
# q1_cryst = Matrix{Float64}(undef, (numq1, 3))
# for iq in axes(q1_cryst, 1)
#     q1_cryst[iq, :] = parse.(Float64, split(q1_file[iq]))
# end

q1_cryst = [0.333333 0.0 0.0]

# Will generate a list of frequencies/energies for which the phasespace 
# numfreqs = 100
# bound_low = 0.01 # THz
# bound_up = 17 # THz
# cont_freqs = collect(range(bound_low, bound_up, numfreqs))

cont_freqs = [
    0.1269330409E-01,
    0.1269330409E-01,
    0.3597569890E-01,
    0.5674301942E-01,
    0.6031045417E-01,
    0.6031045417E-01,
]

smearing = 5e-5
brillouin_sampling = (21, 21, 21)
ps = PhaseSpace(
    ebdata,
    deconvolution,
    sodata,
    q1_cryst,
    cont_freqs,
    smearing;
    brillouin_sampling,
)

phasespace = ps.phasespace
