#!/bin/bash

calc_script_source=$1
numchunks=$2

mkdir data

for i in $(seq 1 "$numchunks"); do
    new_script="calc_$i.jl"
    touch "$new_script"

    echo "# ===This was generated by build_calc_env.sh===" >> "$new_script"
    echo "dist_N = $i" >> "$new_script"
    echo "dist_over_N = $numchunks" >> "$new_script"
    echo "# =============================================" >> "$new_script"
    echo " " >> "$new_script"

    cat "$calc_script_source" >> "$new_script"
done
